export const codeError = {
  apyKeyNoRecibida: { codeError: '2000', msg: 'No se ha recibido un token de acceso válido' },
  ipInautorizadaInactiva: { codeError: '2001', msg: 'La ip de conexión no es válida' },
  apyKeyInautorizadaInactiva: { codeError: '2002', msg: 'El token de acceso se encuentra inautorizado' },
  inicioSesionError: { codeError: '2003', msg: 'Usuario o contraseña incorrecta' },
  existeEmail: { codeError: '2004', msg: 'Email ya se encuenta registrado' },
  informacionIncorrecta: { codeError: '2005', msg: 'Información incorrecta' },
  pinIncorrecto: { codeError: '2006', msg: 'PIN incorrecto' },
  datosIncompletos: { codeError: '2007', msg: 'Todos los campos son requeridos' },
  passwordDebil: { codeError: '2008', msg: 'El password no cumple con los requisitos mínimos de 8 caracteres,  mayúsculas y minúsculas y 1 número' },
  noCargoArchivo: { codeError: '2009', msg: 'No se cargó el archivo' },
  noExistenRegistros: { codeError: '2010', msg: 'No existen registros' },
  codigoTwoFactorIncorrecto: { codeError: '2011', msg: 'Código de segundo factor incorrecto' },
  errorInterno: { codeError: '2012', msg: 'Disculpe las molestias. Por favor comuníquese con soporte' },
  limiteAddress: { codeError: '2013', msg: 'El usuario ya tiene una address asignada a esta moneda' },
  usuarioConrasenaIncorrecta: { codeError: '2014', msg: 'Usuario o contraseña incorrecta' },
  noActualizarInformacion: { codeError: '2015', msg: 'No se puede actualizar la información' },
  emailNoVerificado: { codeError: '2016', msg: 'El email no ha sido verificado' },
  usuarioInactivo: { codeError: '2017', msg: 'El usuario está inactivo' },
  perfilIncompleto: { codeError: '2018', msg: 'El usuario tiene sus datos mínimos incompletos' },
  empresaIncompleta: { codeError: '2019', msg: 'El usuario tiene sus datos mínimos de empresa incompletos' },
  fondosInsuficientes: { codeError: '2020', msg: 'Fondos insuficientes en su balance o supera el monto máximo permitido para el nivel' },
  usuarioIcorrecto: { codeError: '2021', msg: 'El usuario incorrecto' },
  yaExistenRegistros: { codeError: '2022', msg: 'Ya existen registros con estos valores' },
  phoneNoVerificado: { codeError: '2023', msg: 'el número de telefono no ha sido verificado' },
};
